[workspace]
resolver = "2"
members = ["crates/horae-core", "crates/horae-tui", "crates/horae-cli", "crates/horae-gui/src-tauri"]
default-members = ["crates/horae-cli"]

[workspace.package]
version = "0.1.1"
edition = "2021"
rust-version = "1.89"
license = "GPL-3.0"
repository = "https://github.com/zhaohang1205/horae"

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"
opt-level = "z"
